import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsMobile: SidebarsConfig = {
  mobileDocsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsMobile;
