#+title: How to run the react native environment

Follow the following directions to run the environment.

1. *DOWNLOAD NIX* with what applies to you
   - if on WSL: ~sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon~
   - if on Linux-based native system: ~sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon~
   - *Note:* you may need to restart your environment (e.g open a new shell or a new terminal) for nix to be recognized by your system.
     - if after the restart and nix is still undefined in the CLI, enter the following command: ~source /etc/profile.d/nix.sh~
2. *Run the script* ~configure_nix.sh~ with the command ~bash configure_nix.sh~. This script configures your Nix installation to process flakes (the tool we are using to keep things tight).
3. *Build and install the environment* with the command below. This will fetch the tools and set up the environment we will work on. *Note:* you need to be in the ~/.../YLP/mobile-app/~ directory for this to work
    #+BEGIN_SRC bash
    nix develop -L
    cd sapot-mobile-app
    npm install
    #+END_SRC


** TIPS
This section tackles the common errors that I encountered when running the react native environment.
*** Running the Android virtual machine
If you are using WSL2 it is better to install the Android studio natively in Windows then link it to WSL2. You can follow this guide [[https://reactnative.dev/docs/set-up-your-environment][Android studio + WSL2 guide]] (follow the *Android Development Environment*)


*** ADB cannot find the devices
If after running the ~nix develop~ command and the command ~adb devices~ does not show your device run the following:
#+BEGIN_SRC
# run this after you've entered the "nix develop" command
magic-fix                     # will make the phone think the server is running locally
reloadADB                     # will reload the adb server and output the newly detected devices
start-local-android           # command to run the "npx expo start" locally and in android mode
#+END_SRC

*** WSL not able to detect plugged in android devices
Run the following commands in the Powershell (note: not inside WSL)
#+BEGIN_SRC powershell
winget install --interactive --exact dorssel.usbipd-win
usbipd list
#+END_SRC
The last command will output something like:
#+BEGIN_SRC powershell
BUSID  VID:PID    DEVICE                                                        STATE
1-4    04e8:6860  SAMSUNG Android, USB Composite Device                         Not attached
1-10   046d:c52b  Logitech USB Input Device                                     Not attached
#+END_SRC
Select the BUSID of your device and enter the command
#+BEGIN_SRC
sudo usbipd bind --busid 1-4
usbipd attach --wsl --busid 1-4 --auto-attach
#+END_SRC

Go back to WSL and do the following
#+BEGIN_SRC
cd /path/to/flake.nix/directory
nix develop
reloadADB
#+END_SRC

it should work now

** Getting Started

Prerequisites: 
  - Must download *Android Studio*
  - Must have stable internet connection
  - Must be in the folder ~/sapot-mobile-app/~

*** Setup your device and android application
1. To download the application in your device, here is the options:

  - *Connect device to your computer via WIFI*. Your device and computer must be connected to the same Wi-Fi
    - *Open your device*. Navigate through *Settings > About Phone >  Software Information* and then tapping the "build number" row at the bottom seven times. Note that device should be notified that the phone is in developer mode.
    - Then go to *Settings > Developer options* to enable "Wireless Debugging". Tap "Wireless Debugging", choose "Pair device with QR Code"
    - Open the *Android Studio*. Click the three dots and select vitrual device manager. Find the wifi-like icon named "Pair devices using Wi-Fi".
    - *Scan the QR code* using your device. Note that this step is successful if there is a device listed when running ~adb devices~ in terminal

  - *Plugin your device via USB to your computer*. Follow the instruction below:
    - Go to your device. Navigate through *Settings > About Phone >  Software Information* and then tapping the "build number" row at the bottom seven times. Note that device should be notified that the phone is in developer mode.
    - Then go to *Settings > Developer options* to enable "USB debugging".
    - Open terminal, run ~adb devices~, when you see a device listed then you are done 

2. Open terminal, make sure you are inside of the folder ~/sapot-mobile-app~. Run ~npx expo start~ in the current terminal. Then create another terminal. On the new terminal, also in the same folder, run ~npx expo run:android~. This will take time to build the app and don't close the terminal. Once it is finished it will automatically install the app in your device. In the first terminal, you will see that the app is running.

*** Notes:
- you need to download EXPO GO in your phone for this to work
- if you are using VSCode you need to restart the language server to remove the erroneous errors ~control + shift + p~ then enter ~Typescript: Restart TS Server~
