"""baseline schema

Revision ID: 39d8921c6309
Revises: 
Create Date: 2026-08-02 17:59:10.411578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39d8921c6309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistedtoken',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_blacklistedtoken_jti'), 'blacklistedtoken', ['jti'], unique=False)
    op.create_table('conversation',
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('conversation_type', sa.Enum('direct', 'solo', 'sms', name='conversationtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=True)
    op.create_index(op.f('ix_conversation_is_deleted'), 'conversation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_conversation_updated_at'), 'conversation', ['updated_at'], unique=False)
    op.create_table('device_key',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('public_key_b64', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('bound_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_key_device_fingerprint'), 'device_key', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_device_key_user_id'), 'device_key', ['user_id'], unique=False)
    op.create_table('email_recovery_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_recovery_token_token_hash'), 'email_recovery_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_recovery_token_user_id'), 'email_recovery_token', ['user_id'], unique=False)
    op.create_table('guest_sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(length=17), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('hotspot_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disconnected', name='sessionstatus'), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('disconnect_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_sessions_session_id'), 'guest_sessions', ['session_id'], unique=True)
    op.create_table('interfacetraffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rx_bps', sa.Integer(), nullable=False),
    sa.Column('tx_bps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lockout_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempt_device_fingerprint'), 'login_attempt', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_login_attempt_user_id'), 'login_attempt', ['user_id'], unique=False)
    op.create_table('passwordresetcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresetcode_code'), 'passwordresetcode', ['code'], unique=False)
    op.create_index(op.f('ix_passwordresetcode_email'), 'passwordresetcode', ['email'], unique=False)
    op.create_table('passwordresettoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresettoken_token_hash'), 'passwordresettoken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_passwordresettoken_user_id'), 'passwordresettoken', ['user_id'], unique=False)
    op.create_table('phone_password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_password_reset_code_code'), 'phone_password_reset_code', ['code'], unique=False)
    op.create_index(op.f('ix_phone_password_reset_code_phone_number'), 'phone_password_reset_code', ['phone_number'], unique=False)
    op.create_table('recovery_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('recovery_method', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lockout_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempt_device_fingerprint'), 'recovery_attempt', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_recovery_attempt_recovery_method'), 'recovery_attempt', ['recovery_method'], unique=False)
    op.create_index(op.f('ix_recovery_attempt_user_id'), 'recovery_attempt', ['user_id'], unique=False)
    op.create_table('recovery_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_session_token_hash'), 'recovery_session', ['token_hash'], unique=True)
    op.create_index(op.f('ix_recovery_session_user_id'), 'recovery_session', ['user_id'], unique=False)
    op.create_table('recoverykey',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recoverykey_id'), 'recoverykey', ['id'], unique=False)
    op.create_index(op.f('ix_recoverykey_user_id'), 'recoverykey', ['user_id'], unique=True)
    op.create_table('routerhealth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_load', sa.Float(), nullable=False),
    sa.Column('free_memory', sa.Integer(), nullable=False),
    sa.Column('total_memory', sa.Integer(), nullable=False),
    sa.Column('uptime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_created_at'), 'admin', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_index(op.f('ix_admin_user_id'), 'admin', ['user_id'], unique=True)
    op.create_table('announcement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', name='prioritytype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', name='announcementstatustype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('target_audience', sa.Enum('admin', 'user', 'rescuer', name='audiencetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_created_at'), 'announcement', ['created_at'], unique=False)
    op.create_index(op.f('ix_announcement_id'), 'announcement', ['id'], unique=False)
    op.create_index(op.f('ix_announcement_user_id'), 'announcement', ['user_id'], unique=False)
    op.create_table('banneduser',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banneduser_created_at'), 'banneduser', ['created_at'], unique=False)
    op.create_index(op.f('ix_banneduser_id'), 'banneduser', ['id'], unique=False)
    op.create_index(op.f('ix_banneduser_until'), 'banneduser', ['until'], unique=False)
    op.create_index(op.f('ix_banneduser_user_id'), 'banneduser', ['user_id'], unique=True)
    op.create_table('call',
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_type', sa.Enum('audio', 'video', name='calltype'), nullable=False),
    sa.Column('status', sa.Enum('missed', 'completed', 'rejected', 'busy', 'undefined', name='statustype'), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=False),
    sa.Column('end_time', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('initiator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_id'), 'call', ['id'], unique=False)
    op.create_index(op.f('ix_call_is_deleted'), 'call', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_call_updated_at'), 'call', ['updated_at'], unique=False)
    op.create_table('contact_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('peer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_key_owner_id'), 'contact_key', ['owner_id'], unique=False)
    op.create_index(op.f('ix_contact_key_peer_id'), 'contact_key', ['peer_id'], unique=False)
    op.create_table('conversationparticipant',
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversationparticipant_conversation_id'), 'conversationparticipant', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversationparticipant_id'), 'conversationparticipant', ['id'], unique=True)
    op.create_index(op.f('ix_conversationparticipant_updated_at'), 'conversationparticipant', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversationparticipant_user_id'), 'conversationparticipant', ['user_id'], unique=False)
    op.create_table('guest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_created_at'), 'guest', ['created_at'], unique=False)
    op.create_index(op.f('ix_guest_id'), 'guest', ['id'], unique=False)
    op.create_index(op.f('ix_guest_user_id'), 'guest', ['user_id'], unique=True)
    op.create_table('message',
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'file', 'call_log', 'sms', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('linked_message_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_message_id'], ['message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_index(op.f('ix_message_updated_at'), 'message', ['updated_at'], unique=False)
    op.create_table('peer_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ecdh_public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_key_user_id'), 'peer_key', ['user_id'], unique=True)
    op.create_table('phone_verification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('verification_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_verification_expires_at'), 'phone_verification', ['expires_at'], unique=False)
    op.create_index(op.f('ix_phone_verification_id'), 'phone_verification', ['id'], unique=False)
    op.create_index(op.f('ix_phone_verification_is_used'), 'phone_verification', ['is_used'], unique=False)
    op.create_index(op.f('ix_phone_verification_phone_number'), 'phone_verification', ['phone_number'], unique=False)
    op.create_index(op.f('ix_phone_verification_user_id'), 'phone_verification', ['user_id'], unique=False)
    op.create_index(op.f('ix_phone_verification_verification_code'), 'phone_verification', ['verification_code'], unique=False)
    op.create_table('phone_verified',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_verified_id'), 'phone_verified', ['id'], unique=False)
    op.create_index(op.f('ix_phone_verified_user_id'), 'phone_verified', ['user_id'], unique=False)
    op.create_table('queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('to', sa.Uuid(), nullable=True),
    sa.Column('payload_type', sa.String(length=6000), nullable=True),
    sa.Column('data_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.String(length=6000), nullable=True),
    sa.ForeignKeyConstraint(['to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_data_id'), 'queue', ['data_id'], unique=False)
    op.create_index(op.f('ix_queue_id'), 'queue', ['id'], unique=True)
    op.create_table('rescuer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rescuer_created_at'), 'rescuer', ['created_at'], unique=False)
    op.create_index(op.f('ix_rescuer_id'), 'rescuer', ['id'], unique=False)
    op.create_index(op.f('ix_rescuer_user_id'), 'rescuer', ['user_id'], unique=True)
    op.create_table('user_activity',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('userlocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userlocation_id'), 'userlocation', ['id'], unique=False)
    op.create_index(op.f('ix_userlocation_timestamp'), 'userlocation', ['timestamp'], unique=False)
    op.create_index(op.f('ix_userlocation_user_id'), 'userlocation', ['user_id'], unique=False)
    op.create_table('userprofilepicture',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprofilepicture_filename'), 'userprofilepicture', ['filename'], unique=False)
    op.create_index(op.f('ix_userprofilepicture_user_id'), 'userprofilepicture', ['user_id'], unique=False)
    op.create_table('usersecurityquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_burned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_security_question')
    )
    op.create_table('wrapped_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wrapped_blob', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wrapped_key_user_id'), 'wrapped_key', ['user_id'], unique=True)
    op.create_table('wrapped_key_recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wrapped_blob', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recovery_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'method')
    )
    op.create_index(op.f('ix_wrapped_key_recovery_method'), 'wrapped_key_recovery', ['method'], unique=False)
    op.create_index(op.f('ix_wrapped_key_recovery_user_id'), 'wrapped_key_recovery', ['user_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=False)
    op.create_table('callparticipant',
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.BigInteger(), nullable=False),
    sa.Column('left_at', sa.Integer(), nullable=True),
    sa.Column('call_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callparticipant_call_id'), 'callparticipant', ['call_id'], unique=False)
    op.create_index(op.f('ix_callparticipant_id'), 'callparticipant', ['id'], unique=False)
    op.create_index(op.f('ix_callparticipant_is_deleted'), 'callparticipant', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_callparticipant_updated_at'), 'callparticipant', ['updated_at'], unique=False)
    op.create_index(op.f('ix_callparticipant_user_id'), 'callparticipant', ['user_id'], unique=False)
    op.create_table('messagereceipt',
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('read', 'delivered', 'sent', name='statustype'), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messagereceipt_id'), 'messagereceipt', ['id'], unique=False)
    op.create_index(op.f('ix_messagereceipt_is_deleted'), 'messagereceipt', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_messagereceipt_updated_at'), 'messagereceipt', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Adjusted from autogenerate output: the generated per-index
    # op.drop_index() calls were removed. DROP TABLE already drops that
    # table's indexes on every backend, and on MySQL dropping an index that
    # backs a foreign key fails outright (error 1553), which left the
    # downgrade half-applied. Table order below is unchanged.
    op.drop_table('messagereceipt')
    op.drop_table('callparticipant')
    op.drop_table('attachment')
    op.drop_table('wrapped_key_recovery')
    op.drop_table('wrapped_key')
    op.drop_table('usersecurityquestion')
    op.drop_table('userprofilepicture')
    op.drop_table('userlocation')
    op.drop_table('user_activity')
    op.drop_table('rescuer')
    op.drop_table('queue')
    op.drop_table('phone_verified')
    op.drop_table('phone_verification')
    op.drop_table('peer_key')
    op.drop_table('message')
    op.drop_table('guest')
    op.drop_table('conversationparticipant')
    op.drop_table('contact_key')
    op.drop_table('call')
    op.drop_table('banneduser')
    op.drop_table('announcement')
    op.drop_table('admin')
    op.drop_table('activity_logs')
    op.drop_table('user')
    op.drop_table('routerhealth')
    op.drop_table('recoverykey')
    op.drop_table('recovery_session')
    op.drop_table('recovery_attempt')
    op.drop_table('phone_password_reset_code')
    op.drop_table('passwordresettoken')
    op.drop_table('passwordresetcode')
    op.drop_table('login_attempt')
    op.drop_table('interfacetraffic')
    op.drop_table('guest_sessions')
    op.drop_table('email_recovery_token')
    op.drop_table('device_key')
    op.drop_table('conversation')
    op.drop_table('blacklistedtoken')
    # ### end Alembic commands ###
