#+title: Documentation
run the API with the command ~uvicorn app.main:app --reload --host=0.0.0.0~
* SEE ~/docs~ for more comprehensive documentation

* TODO what i need for ~/auth~:
** Sign up:
  sign up with the following
  1. username -> should be *firstname* then *lastname*
  2. phone number
  3. email
  4. password hash
  5. security questions
** login with:
  - [X] username/email/number
  - [X] password
** password recovery  through:
  - [X] security questions
  - [X] downloadable recovery key
  - [ ] SMS
  - [X] email
** search profiles function (endpoint din to)
- [ ] searchable users within the app
- [ ] can initiate contact through the app
** websockets
*** create web socket endpoint for
- [ ] messaging
  - [ ] group messaging
  - [ ] end to end encryption (RSA)
- [ ] peering information
  - [ ] SDP offer
  - [ ] SDP answer
  - [ ] ICE candidate
  - [ ] ICE servers (optional for remote networks)
- [ ] calling (through the app, no server is needed)

* TODO server features ~/features~
** SMS messaging
** [X] websockets peer to peer initiate
** [ ] GPS mapping
** [ ] Group messaging (tentative)

* Note
Authenticated means the user has to send an authorization header in this format
#+BEGIN_SRC json
{
    "Authorization": "Bearer <access_token>"
}
#+END_SRC

* Endpoints
** Ping endpoint ~/ping GET~
- returns timestamp for measuring latency between client and server
  #+BEGIN_SRC json
    {"status":"ok","timestamp":1772410305.0920138}
  #+END_SRC
- this endpoint can be used like this
  #+BEGIN_SRC javascript
async function measureLatency() {
    const start = performance.now();
    await fetch("http://localhost:8000/ping");
    const end = performance.now();
    return end - start; // milliseconds
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}


(async ()=>{
    let successes = 0;
    for (let i = 0; i < 4; i++) {
        try {
            await measureLatency()
            successes++
        } catch {
            fails++
        }
        await sleep(1000)
    }
    console.log(`${successes/4 * 100}% success rate`) // if 3 of the 4 pings is a success then this will output -> 75% success rate
})()
#+END_SRC
** INFO Endpoint ~/ GET 1.1~
- returns a string if the API is running
- ~{"state": "running"}~

** INFO endpoint ~/auth GET~
- returns a string if the ~/auth~ endpoint is running
- ~{ 'status': 'auth endpoint is running properly' }~

** INFO point ~/auth/exists GET~
- returns a ~{exists: boolean}~ value to any of these fields: username,
  phone number, ID, or email
*** Sample Request
#+BEGIN_SRC json
<link>/auth/exists?identifier=<username, email, or phonenumber>
#+END_SRC
** Change Password ~/auth/change-password POST~
    - requires users to be authenticated
    - send a form body with ~current_password~ and ~new_password~
** Get Token Endpoint~/auth/token POST~
- this endpoint requires two form-data arguments:
  1. username
  2. password
- the ~username~ is actually an *email address*. It is named ~username~ as per compliance
  with the oauth2 standard
- the password is any string
** Create account endpoint ~/auth/ POST~
- this is an example form-data (body) that should be sent to the API
*** Sample Request
with form-data/request body
#+BEGIN_SRC json
{
    "first_name": "Test", // min=2, max=50
    "username": "TestUser", // min=2, max=50
    "last_name": "Test", // min=2, max=50
    "phone_number": "+23960206981",
    "email": "user@example.com",  // email string
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", // UUID, optional
    "password": "Test1234" // min=8, max=128, with digits and upper and lower case letters
}
#+END_SRC
- the ~id~ field is optional
- the password field should have upper and lower case letter. At least one
  number is also required

*** Sample Response
#+BEGIN_SRC json
{
  "username": "johndoe3",
  "first_name": "John",
  "last_name": "Doe",
  "phone_number": null,
  "email": null,
  "id": "f5da3a69-26f7-464f-a3ae-bb25b8bfe124",
  "detail": "Account created.",
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMS0wOTU0NkBnLmJhdHN0YXRlLXUuZWR1LnBoIiwiZXhwIjoxNzcxNDcxMzMxfQ.X4Xp250Zafs7mIXDvjPAASfQKZUG6MyEnYZJAzfRK4E",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMS0wOTU0NkBnLmJhdHN0YXRlLXUuZWR1LnBoIiwiZXhwIjoxNzcxNDcxMzMxfQ.X4Xp250Zafs7mIXDvjPAASfQKZUG6MyEnYZJAzfRK4i",
}
#+END_SRC

** Login ~/auth/token POST~
- this endpoint accepts two arguments: ~username~ and ~password~

*** Sample Request
with request body/form-data
#+BEGIN_SRC json
{
    "username": "TestUser",
    "password": "Test1234"
}
#+END_SRC
- the ~username~ field can be email, username, phone_number, or user id

*** Sample Response
#+BEGIN_SRC json
{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMS0wOTU0NkBnLmJhdHN0YXRlLXUuZWR1LnBoIiwiZXhwIjoxNzcxNDcxMzMxfQ.X4Xp250Zafs7mIXDvjPAASfQKZUG6MyEnYZJAzfRK4E",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMS0wOTU0NkBnLmJhdHN0YXRlLXUuZWR1LnBoIiwiZXhwIjoxNzcxNDcxMzMxfQ.X4Xp250Zafs7mIXDvjPAASfQKZUG6MyEnYZJAzfRK4i",
  "token_type": "bearer"
}
#+END_SRC

*NOTE:* Refresh token will be used to refresh the access token in case it expires

** Refresh Token ~/auth/refresh POST~
send a request with the following form data
#+BEGIN_SRC json
{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NmI3MjgzOS1lMDc3LTQ0MTMtOTFlNi1kMzAzOGM2YTk1MzIiLCJqdGkiOiI5NzIxNTlkNy05NTdkLTRhYmQtOWQxNi1iMTRiYjcyYWE1YTAiLCJ0eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDA2MTI4OX0.bzVjgg74WikXOFTP6kIav0M2kCvP99WlmX8GGueM6pg"
}
#+END_SRC
sample response
#+BEGIN_SRC json
{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NmI3MjgzOS1lMDc3LTQ0MTMtOTFlNi1kMzAzOGM2YTk1MzIiLCJqdGkiOiI1ZWFkNjQ1Yy1lNWQ0LTQ4YzctODI0Yi02ZTk2MDZiMTE5YzIiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0ODc5MTg1fQ.1pq4cTmpZEyyBBrZlr5Oe7OmTmsc0zXe-Y0RpsI4e6o",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NmI3MjgzOS1lMDc3LTQ0MTMtOTFlNi1kMzAzOGM2YTk1MzIiLCJqdGkiOiIwMGNkM2YxNC01MjQwLTQ5MTEtOTMzYy0yNDY2NzQ0MDg5OWQiLCJ0eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDA2MTM4NX0.DX0L_iDRq858J4a_8v6S-onijwRTqpiRfU5-YVcfaA0",
  "token_type": "bearer"
}
#+END_SRC
*The response should be the new refresh and access token.* The old ones are now unusable.

** Generate recovery key ~/auth/forgot-password/generate-new-recovery-key POST~
  - this endpoint requires the user to be /authenticated/
  - no arguments required
  - response is the recovery file


** recovery account with recovery key ~/auth/forgot-password/recovery-with-recovery-key~
- requires two arguments
- recovery key expires after one use
*** Sample Request
with url parameter
#+BEGIN_SRC txt
<link>?user_identifier=<username_email_or_id>
#+END_SRC

with request body
#+BEGIN_SRC json
{
    key_file: File() // recovery file
}
#+END_SRC
*** Sample response
#+BEGIN_SRC json
{
    "recovery-link": "localhost:8000/auth/forgot-password/reset-password?token=EMs-6ZYdWMrpAkeMVK8hdLxfc65vJB6wjGXzEZ2xWrI",
    "method": "POST",
    "expire_in_seconds": 1800
}
#+END_SRC


** reset password ~/auth/forgot-password/reset-password GET~
- requires the ~token~ argument
- will give a ~detail~ response regarding request status
*** Sample Request
with URL parameter
#+BEGIN_SRC json
<link>?token=<token>
#+END_SRC
*** Sample response
  #+BEGIN_SRC json
{
    "detail": "Valid token. Use POST request."
}
  #+END_SRC


** reset password ~/auth/forgot-password/reset-password POST~
- requires the ~token~ argument
- will give a ~detail~ response regarding request status
*** Sample Request
with url parameter
#+BEGIN_SRC json
<link>?token=<token>
#+END_SRC
with request body
#+BEGIN_SRC json
{
  "new_password": "stringst" // new_password must have capital, lowecase, and a number. It's at least 8 characters long
}
#+END_SRC
*** Sample response
  #+BEGIN_SRC json
{
  "message": "password updated successfully."
}
  #+END_SRC

** forgot password ~/auth/forgot-password/email POST~
- sends email to user mail (the email includes a link to the /reset-password end
  point)
*** sample response
#+BEGIN_SRC json
{
    "message": "If the account exists, a reset link was sent."
}
#+END_SRC

** Add security questions ~/auth/forgot-password/security-questions POST~
This endpoint requires user to be authenticated
*** Sample Request
with form data (can be multiple question and answers in one request)
#+BEGIN_SRC json
[{
    "question": "What is your mother'\''s maiden name?",
    "answer": "Smith"
}]
#+END_SRC
*** Sample response
#+BEGIN_SRC json
{
  "message": "Security questions saved successfully."
}
#+END_SRC

** Get security questions ~/auth/forgot-password/security-question POST~
*** Sample Request
with url parameter
#+BEGIN_SRC json
<link>?identifier=johndoe
#+END_SRC
*** Sample response
#+BEGIN_SRC json
{
  "question": "What is your mother's maiden name?"
}
#+END_SRC

** Get security questions ~/auth/forgot-password/security-question/answer POST~
*** Sample Request
with url parameter
#+BEGIN_SRC json
<link>?identifier=johndoe
#+END_SRC

with request body/form-data
#+BEGIN_SRC json
{
  "question": "What is your mother's maiden name?",
  "answer": "Smith"
}
#+END_SRC

*** Sample response
#+BEGIN_SRC json
{
  "correct": true,
  "reset_link": "localhost:8000/auth/forgot-password/reset-password?token=iIVaJOGsKMpZL1hxg6uo3dFUyNv-P-beDSW3MCvgZ9s"
}
#+END_SRC

** Generate security question ~/auth/forgot-password/generate-security-question GET~
requires user to be authenticated
*** Sample Response
#+BEGIN_SRC json
{
  "question": "What's something that you believe that most other people don't?"
}
#+END_SRC
** Verify email ~/auth/verify/email GET~
requires token url parameter sent to a user email. Responds with an html page
** Verify email ~/auth/verify/resend-verification-email GET~
requires user to be authenticated

** Websocket/signalling
*** SDP relay example ~/ws GET~
- access like
  ~https://ylp-software.onrender.com/ws/?target_id=8380dbb9-482e-42fa-a1fd-fafedd9f918d&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOWM4ZDRlYS00OGYwLTRiN2UtYWY1Mi0yZDNmY2FkMGU2OGQiLCJleHAiOjE3NzI0NTU2MDh9.aD-vGqlRHdx_-zHm9Oev12VKCvOoU9MhLm-7rTLnNok&my_id=09c8d4ea-48f0-4b7e-af52-2d3fcad0e68d~.
  Notice the url parameters of my_id, target_id, and token (access_token).

*** SDP relay ~ws://localhost:8000/ws/~ (not visible on the docs)
- this is an endpoint that will be used for relaying SDP offers, answers, and
  ICE candidates
- this endpoint will accept sdp offers, sdp answers, and ICE candidates.
  Anything else will be rejected.
**** Sample Connection to websocket
  #+BEGIN_SRC json
  ws://localhost:8000/ws/?target_id=${client_id}&token=${token}
  #+END_SRC
  Put this link url (change domain as needed but it needs ws:// or wss:// at the
  protocol) inside a WebSocket object, then send a sdp message like
  #+BEGIN_SRC json
    {
        "type": "offer",
        "from_user": "550e8400e29b41d4a716446655440000",
        "to": "619176107fed4af4abb235dc9663136d",j
        "data":  {"some_data": {"here_like":"this"}}
    }
  #+END_SRC

  *Note that the ~from~ and ~to~ should be the same as the connection parameters*

***** TODO
****** ADD TYPES
  - ice-candidate
  - offer
  - answer
  - handshake
******  change structure
#+BEGIN_SRC
      {
        type: "";
        data: {
            from: UUID; to: UUID, ipAddress: string; port: number };
        }
#+END_SRC

** update user info ~/update/profile POST~
can take in different fields to update (can leave fields that won't be updated blank)
with request body/form-data
#+BEGIN_SRC json
{
  "username": "string", // optional
  "first_name": "string", // optional
  "last_name": "string", // optional
  "phone_number": "86410482368", // optional
  "email": "user@example.com" // optional
}
#+END_SRC
** Sync from server ~/sync/pull POST~
Requires users to be authenticated.

Send a request like:
~http://localhost:8000/sync/pull?last_pulled_at=0&schema_version=1~
*** /last_sync_at/ argument
- meant to be the point where the syncing will start
*** /limit/ argument
- amount of data that will be sync in the current connection
- a device can send multiple sync request if there are a lot of data to sync
  from server

*** Example response
#+BEGIN_SRC json
{
  "changes": {
    "conversations": {
      "created": [
        {
          "updated_at": 1775315958000,
          "is_deleted": false,
          "title": "Project Alpha Sync",
          "created_at": 1775315958000,
          "id": "a1646700-6467-42f2-901b-9f936f6d2b63",
          "conversation_type": "group"
        }
      ],
      "updated": [],
      "deleted": []
    },
    "messages": {
      "created": [],
      "updated": [],
      "deleted": []
    },
    "conversation_participants": {
      "created": [],
      "updated": [],
      "deleted": []
    },
    "calls": {
      "created": [],
      "updated": [],
      "deleted": []
    },
    "call_participants": {
      "created": [],
      "updated": [],
      "deleted": []
    },
    "message_receipts": {
      "created": [],
      "updated": [],
      "deleted": []
    }
  },
  "timestamp": 1775289283482
}
#+END_SRC

** Sync to server ~/sync/push POST~
Requires users to be authenticated.


use this endpoint to push new data to the server
*** attach the following as the form-body
#+BEGIN_SRC json
{
  "changes": {
    "conversations": {
      "created": [
        {
          "id": "conv_id_placeholder",
          "title": "New Test Chat",
          "conversation_type": "group",
          "created_at": 1712234500000,
          "updated_at": 1712234500000,
          "is_deleted": false
        }
      ],
      "updated": [],
      "deleted": []
    },
    "messages": {
      "created": [
        {
          "id": "msg_id_placeholder",
          "content": "Hello World",
          "conversation_id": "conv_id_placeholder",
          "sender_id": "user_id_placeholder",
          "created_at": 1712234500001,
          "updated_at": 1712234500001,
          "is_deleted": false
        }
      ],
      "updated": [],
      "deleted": []
    }
  },
  "last_pulled_at": 1712234000000
}

// OR
{
  "changes": {
    "additionalProp1": {
      "created": [...],
      "updated": [...],
      "deleted": [...]
    },
    "additionalProp2": {
      "created": [],
      "updated": [],
      "deleted": []
    },
    "additionalProp3": {
      "created": [],
      "updated": [],
      "deleted": []
    }
  },
  "last_pulled_at": 0
}
#+END_SRC
*** Sample response

#+BEGIN_SRC json
{
  "status": "ok"
}
#+END_SRC

*** Sample data to send (same data format will be sent when syncing from server)
#+BEGIN_SRC python
push_payload = {
    "conversations": [
        {
            "id": conv_id,
            "title": "Sync Test",
            "conversation_type": "group",
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
    ],
    "conversation_participants": [
        {
            "id": part_id,
            "conversation_id": conv_id,
            "user_id": user_id,
            "joined_at": datetime.now(timezone.utc).isoformat(),
            "is_deleted": False
        }
    ],
    "messages": [
        {
            "id": msg_id,
            "conversation_id": conv_id,
            "content": "Reconciliation check",
            "message_type": "text",
            "is_deleted": False,
            "created_at": datetime.now(timezone.utc).isoformat()
        }
    ],
    "calls": [
        {
            "id": str(call_id),
            "call_type": "video",  # CallType.AUDIO
            "status": "completed", # StatusType.COMPLETED
            "start_time": datetime.now(timezone.utc).isoformat(),
            "end_time": datetime.now(timezone.utc).isoformat(),
            "conversation_id": str(conv_id),
            "initiator_id": str(user_id)
        }
    ],
    "call_participants": [
        {
            "id": str(uuid4()),
            "conversation_id": str(conv_id),
            "user_id": str(user_id),
            "joined_at": datetime.now(timezone.utc).isoformat(),
            "left_at": None
        }
    ],
    "message_receipts": [
        {
            "id": str(uuid4()),
            "status": "read", # StatusType.READ
            "message_id": str(msg_id),
            "user_id": str(user_id),
            "updated_at": datetime.now(timezone.utc).isoformat()
        }
    ]
}
    #+END_SRC

** Profile picture endpoints
*** /profile-picture/me (GET)
use this endpoint to get the current user's profile picture link
**** Response
#+BEGIN_SRC json
{
    "url": "/static/profile_pictures/8c78cb1c-c19f-4442-825c-8099594379be_aa5a9e.jpg"
}
#+END_SRC
use the format "{domain}/{url}" to access the photo
*** /profile-picture/me (POST)
use a multi-part form data to upload photos
**** curl example
#+BEGIN_SRC bash
curl -X 'POST' \
    'http://localhost:8000/profile-picture/me' \
    -H 'accept: application/json' \
    -H 'Authorization: Bearer <token> \
    -H 'Content-Type: multipart/form-data' \
    -F 'file=@pic.jpg;type=image/jpeg'
#+END_SRC
**** Response
#+BEGIN_SRC json
{
    "message": "Photo uploaded successfully",
    "photo_id": "0b31655b-ce64-4f32-90e7-c7973b726580",
    "url": "/static/profile_pics/8c78cb1c-c19f-4442-825c-8099594379be_a9ec8c.jpg"
}
#+END_SRC
use the format "{domain}/{url}" to access the photo

*** /profile-picture/{user-id}
    use this to get the profile picture of other users
**** sample request ~http://localhost:8000/profile-picture/96b72839-e077-4413-91e6-d3038c6a9532~
**** sample response ~{"url": "/static/default.jpg"}~
**** use the format "{domain}/{url}" to access the photo

** GPS 
*** Websocket 
**** real-time gps data upload (for regular users) ~/gps/ws/{user_id}~ 
use this end point for users to upload their location
***** sample usage
#+BEGIN_SRC json
const WebSocket = require('ws'); // npm install ws

// Replace with your actual user_id and server URL
const USER_ID = '8c78cb1c-c19f-4442-825c-8099594379be'; 
const url = `ws://localhost:8000/gps/ws/${USER_ID}`;

const ws = new WebSocket(url);

ws.on('open', () => {
    console.log('Connected to FastAPI GPS Stream');

    // Simulate sending a coordinate every 3 seconds
    setInterval(() => {
        const payload = {
            lat: 14.5995 + (Math.random() * 0.01), // Random jitter
            lng: 120.9842 + (Math.random() * 0.01)
        };
        
        console.log('Sending:', payload);
        ws.send(JSON.stringify(payload));
    }, 3000);
});

ws.on('message', (data) => {
    console.log('Message from server:', data.toString());
});

ws.on('error', (err) => {
    console.error('Connection Error:', err);
});

ws.on('close', () => {
    console.log('Connection closed');
});
#+END_SRC
**** real-time monitoring of gps upload of users (for rescuers) ~/gps/ws/monitor/rescuers/{rescuer_id}~ 
use this end point for rescuers to receive and monitor user locations
***** sample usage
#+BEGIN_SRC json
const WebSocket = require('ws');

// 1. Replace with a valid Rescuer ID from your MariaDB 'rescuer' table
const RESCUER_ID = "25e00987e2854317a681e83ee57d41b5"; 
const url = `ws://localhost:8000/gps/ws/monitor/rescuers/${RESCUER_ID}`;

console.log(`Connecting to Monitor as Rescuer: ${RESCUER_ID}...`);
const ws = new WebSocket(url);

ws.on('open', () => {
    console.log('✅ Connected! Standing by for live GPS updates from users...');
});

ws.on('message', (data) => {
    const payload = JSON.parse(data);
    
    console.log('\n--- 📍 LIVE SIGNAL RECEIVED ---');
    console.log(`User ID:   ${payload.user_id}`);
    console.log(`Location:  ${payload.latitude}, ${payload.longitude}`);
    console.log(`Time:      ${payload.timestamp}`);
    console.log('-------------------------------\n');
});

ws.on('error', (err) => {
    console.error('❌ Connection Error:', err.message);
});

ws.on('close', (code, reason) => {
    console.log(`\n🔌 Connection Closed (Code: ${code}, Reason: ${reason || 'None'})`);
});
#+END_SRC
*** Endpoints ~GET/POST~
**** retrieve all latest locations (all hosts) ~/gps/latest GET~
requires a rescuer to be authenticated
***** sample output
#+BEGIN_SRC json
[
  {
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be",
    "latitude": 14.606558629224603,
    "longitude": 120.98807070190405,
    "timestamp": "2026-04-02T03:40:56.615873"
  },
  {
    "user_id": "123bj879-c19f-4442-825c-8099594379be",
    "latitude": 14.606558629224603,
    "longitude": 123.98807070190405,
    "timestamp": "2026-04-03T03:40:56.615873"
  }
]
#+END_SRC

**** retrieve all of a specific user's locations ~/gps/history/{user_id}~
requires a rescuer to be authenticated


Returns all the gps history of a user.


Use a router parameter like ~http://localhost:8000/gps/history/e51bb26d-e18a-4e30-afe5-a9fbd1697cb1?limit=50~. 
***** Sample Response
#+BEGIN_SRC json
[
  {
    "latitude": 14.606558629224603,
    "id": "c4a2a2c5-d618-4a77-8094-7bd6648d7be2",
    "timestamp": "2026-04-02T03:40:56.615873",
    "longitude": 120.98807070190405,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.600755618961887,
    "id": "433ab19f-f6b8-4c33-8c0a-4d815b1f90e3",
    "timestamp": "2026-04-02T03:40:53.614636",
    "longitude": 120.99229108308664,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.601045471500155,
    "id": "cbadf576-0786-4ac1-88f9-0fd6a4852193",
    "timestamp": "2026-04-02T03:40:50.611807",
    "longitude": 120.98925193962702,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.608608377680218,
    "id": "8fd95f67-88fa-4005-b2db-144b239381aa",
    "timestamp": "2026-04-02T03:40:47.607335",
    "longitude": 120.99151386823995,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.600557283850444,
    "id": "d504405e-afd4-4117-aa14-9b6106210659",
    "timestamp": "2026-04-02T03:40:44.604044",
    "longitude": 120.9847839668106,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.601115593510729,
    "id": "3441322a-1160-480f-b791-3817e4851b9b",
    "timestamp": "2026-04-02T03:40:41.601114",
    "longitude": 120.9920237339332,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.603723200573773,
    "id": "c4ea9ee1-787c-445e-9f26-32fae881740a",
    "timestamp": "2026-04-02T03:40:38.597178",
    "longitude": 120.98755365309675,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.6008293763081,
    "id": "76c5f9cd-bb48-4e74-8015-a91929377f17",
    "timestamp": "2026-04-02T03:40:35.593107",
    "longitude": 120.985738955812,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.601966468839759,
    "id": "0ffced18-785c-4e61-a3eb-bef75fc943a9",
    "timestamp": "2026-04-02T03:40:32.593173",
    "longitude": 120.99113153367198,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.602889471352492,
    "id": "d18894f7-d194-4d02-a1e3-bead120c3294",
    "timestamp": "2026-04-02T03:40:29.599866",
    "longitude": 120.98856682197038,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.60685971554244,
    "id": "760abf67-4686-45c6-9ddb-1d3def4ef310",
    "timestamp": "2026-04-02T02:57:03.086158",
    "longitude": 120.98579097626569,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.60363679181401,
    "id": "fdc3c67d-ed09-4223-abcb-8e3c4bcf528d",
    "timestamp": "2026-04-02T02:57:00.081247",
    "longitude": 120.98465649614077,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.607077018033639,
    "id": "8c52181a-4fb7-46f7-bce7-0cd41f01a1d1",
    "timestamp": "2026-04-02T02:56:57.079425",
    "longitude": 120.99254194749294,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.603596652337677,
    "id": "4da113d7-eaf7-4388-af69-bec831bb7214",
    "timestamp": "2026-04-02T02:56:54.120250",
    "longitude": 120.99002974057063,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.599582724610945,
    "id": "7580a102-c701-47fa-9c3a-6bb919eb564b",
    "timestamp": "2026-04-02T02:56:54.085186",
    "longitude": 120.99088677322926,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.602520965545942,
    "id": "0844e314-5f4c-4c72-8619-74d6bffa5226",
    "timestamp": "2026-04-02T02:56:51.126538",
    "longitude": 120.98588492879331,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.603922374078751,
    "id": "68d752d5-b48b-4339-87db-21446e7a4b27",
    "timestamp": "2026-04-02T02:49:49.073195",
    "longitude": 120.9849139052611,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.603904968268075,
    "id": "d3e41049-bad5-41f7-989a-855abeb41b03",
    "timestamp": "2026-04-02T02:49:46.070323",
    "longitude": 120.98670000998804,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.60029975152173,
    "id": "c1c42901-b05a-4e4f-9122-ec853fa756e5",
    "timestamp": "2026-04-02T02:49:43.067378",
    "longitude": 120.98733195726429,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.602567108736677,
    "id": "afa3d3b6-434e-47cf-a7ad-b437ebec4127",
    "timestamp": "2026-04-02T02:49:40.063227",
    "longitude": 120.9883193189707,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.600345171047904,
    "id": "10bfbe39-35e8-492e-ab50-76531feb75ac",
    "timestamp": "2026-04-02T02:49:37.062248",
    "longitude": 120.98494143339833,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.606047580346427,
    "id": "899c782c-69dc-428a-b659-b81d3e14e007",
    "timestamp": "2026-04-02T02:49:34.068026",
    "longitude": 120.98852613903374,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.605990462420985,
    "id": "2d863905-8c37-4cf8-881e-b75dd220edfb",
    "timestamp": "2026-04-02T02:30:20.024999",
    "longitude": 120.99089730633138,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.603717947654456,
    "id": "7c11c7b7-d4fc-43e9-ac01-a95e91f328bd",
    "timestamp": "2026-04-02T02:30:17.020718",
    "longitude": 120.99117005374906,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.605704985823998,
    "id": "f8f9fab5-16d0-4981-8701-a9d31acd2dfc",
    "timestamp": "2026-04-02T02:30:14.019117",
    "longitude": 120.98438451274777,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.607982766242934,
    "id": "c49be2e5-957e-42bd-a7c0-31fcde1e14e1",
    "timestamp": "2026-04-02T02:30:11.017697",
    "longitude": 120.98516675036065,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.608876156323657,
    "id": "36d36ccb-ac44-49f9-91cb-6706681481da",
    "timestamp": "2026-04-02T02:30:08.014158",
    "longitude": 120.98648665485895,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.608085026241573,
    "id": "ff694bea-3cca-46a3-b168-d65622b11fd7",
    "timestamp": "2026-04-02T02:30:05.010644",
    "longitude": 120.99253435981146,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.605254794938972,
    "id": "bdbf3320-1391-4bf9-9131-09cacfe5ce47",
    "timestamp": "2026-04-02T02:30:02.010270",
    "longitude": 120.99121916423687,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.608697808504377,
    "id": "72277272-088d-4ba2-b34e-343b829a0e19",
    "timestamp": "2026-04-02T02:29:59.017917",
    "longitude": 120.99024543520125,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.607334213959602,
    "id": "6e771b7c-16f1-41c3-883a-f686d082d452",
    "timestamp": "2026-04-01T22:27:07.951543",
    "longitude": 120.99195486644723,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.602121816049662,
    "id": "b7cedcfe-235d-43e6-be27-deadf1e354af",
    "timestamp": "2026-04-01T22:27:04.950283",
    "longitude": 120.98883886523085,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.608928718456086,
    "id": "7ec09fbe-88b1-4fd1-b906-9a6a33ad5654",
    "timestamp": "2026-04-01T22:27:01.957087",
    "longitude": 120.98447443078867,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.604874231839656,
    "id": "316ee009-0b50-480d-9015-57aafc6f57c0",
    "timestamp": "2026-04-01T22:25:06.330184",
    "longitude": 120.9888422700312,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.602288373854263,
    "id": "8609d122-f772-44f3-8e45-305c830eda75",
    "timestamp": "2026-04-01T22:25:03.326013",
    "longitude": 120.99066151636902,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.608663054820651,
    "id": "87eaebc4-48cb-474c-b42b-4215f817ed2c",
    "timestamp": "2026-04-01T22:25:00.321648",
    "longitude": 120.98577533671543,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.603278803142178,
    "id": "baef8be4-afd6-4f29-9754-9bcbad97cbb2",
    "timestamp": "2026-04-01T22:24:57.318175",
    "longitude": 120.99378508458786,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.605729601072065,
    "id": "c0166004-7fc1-4076-be7a-edf30f18f2fc",
    "timestamp": "2026-04-01T22:24:54.317997",
    "longitude": 120.98593488628765,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.600383719548532,
    "id": "c51e2b05-78e9-4444-a9dd-8d9f0c60ac71",
    "timestamp": "2026-04-01T22:24:51.315125",
    "longitude": 120.9908577981012,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.607738962339551,
    "id": "bfd8eabb-064e-413b-8561-8c55043fb8fe",
    "timestamp": "2026-04-01T22:24:48.312131",
    "longitude": 120.98840046401102,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.604201839476813,
    "id": "e3fef08e-ced3-482c-a325-6e10f4c5fe81",
    "timestamp": "2026-04-01T22:24:45.308708",
    "longitude": 120.98547535836593,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.607626640181296,
    "id": "91499234-42d7-47ac-8b2d-c8a93e89c67f",
    "timestamp": "2026-04-01T22:24:42.305847",
    "longitude": 120.98902017891639,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.606900453670596,
    "id": "d035b1b4-7cc5-4b96-a126-c5a8a67dd071",
    "timestamp": "2026-04-01T22:24:39.302451",
    "longitude": 120.9897946979055,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.601431390509765,
    "id": "64731b3a-9b3e-48c5-9bd1-eb6cddc7370f",
    "timestamp": "2026-04-01T22:24:36.299976",
    "longitude": 120.99359629760265,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.604504740612574,
    "id": "edfa2f19-e460-4ad9-b769-ff295bfaf8ef",
    "timestamp": "2026-04-01T22:24:33.297174",
    "longitude": 120.98891404888941,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.600631544501828,
    "id": "1830dcf1-acbd-4a2b-8adb-351a915b0beb",
    "timestamp": "2026-04-01T22:24:30.294635",
    "longitude": 120.98584625617286,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.606862426372096,
    "id": "e5cff5fa-eda6-4688-8a5d-38d0081ddd38",
    "timestamp": "2026-04-01T22:24:27.291453",
    "longitude": 120.99373044376074,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.606952886419549,
    "id": "22e7f227-eb16-4c41-a4cf-27ad48b1a3fd",
    "timestamp": "2026-04-01T22:24:24.288491",
    "longitude": 120.993064635643,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.609253071748658,
    "id": "a65fb8e3-f0b5-4b68-b6e3-7ef37b2b97b6",
    "timestamp": "2026-04-01T22:24:21.286170",
    "longitude": 120.98438640759677,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  },
  {
    "latitude": 14.605266467090093,
    "id": "2211a49e-c9ba-4191-9111-353c8b5088c6",
    "timestamp": "2026-04-01T22:24:18.282085",
    "longitude": 120.99404368266717,
    "user_id": "8c78cb1c-c19f-4442-825c-8099594379be"
  }
]
#+END_SRC

** websocket responses
*** get online users
To get the online users, send a ws request to ~/ws/~ containing ~{ type: 'get-active-users' }~


The server would response with the list of user IDs that are currently active


Everytime a user connected to his/her dedicated websocket, a ~{type: "status-update", "user_id": user_id, "status": "online"}~ json will be broadcasted to everyone


Everytime a user disconnects, a ~{"type": "status-update","user_id": user_id, 'status': "offline"}~ will be broadcasted

*** Relay New Message TYPES
For now let's call it MessageData


use a request like:
#+BEGIN_SRC json
{
	type: 'call-ended', // Options: 'audio-call', 'video-call', 'call-ended'
	data: {
		from: '550e8400-e29b-41d4-a716-446655440000', // Your sender ID
		to: '96eaba99-3797-4c2c-9174-92e3a7dfe7bc'    // Target user UUID
	}
}
#+END_SRC
to the ~/ws/~ websocket endpoint


this will be queued in the webserver in case the user receiving was offline 


this will also be sent to the user in case the user comes online (connect to the websocket again)
