#+title: Documentation
run the API with the command ~uvicorn app.main:app --reload --host=0.0.0.0~
* SEE ~/docs~ for more comprehensive documentation

* TODO what i need for ~/auth~:
** Sign up:
  sign up with the following
  1. username -> should be *firstname* then *lastname*
  2. phone number
  3. email
  4. password hash
  5. security questions
** login with:
  - [X] username/email/number
  - [X] password
** password recovery  through:
  - [X] security questions
  - [X] downloadable recovery key
  - [ ] SMS
  - [X] email
** search profiles function (endpoint din to)
- [ ] searchable users within the app
- [ ] can initiate contact through the app
** websockets
*** create web socket endpoint for
- [ ] messaging
  - [ ] group messaging
  - [ ] end to end encryption (RSA)
- [ ] peering information
  - [ ] SDP offer
  - [ ] SDP answer
  - [ ] ICE candidate
  - [ ] ICE servers (optional for remote networks)
- [ ] calling (through the app, no server is needed)

* TODO ~/sync POST~
** choose timestamps on how to execute syncing

* TODO server features ~/features~
** SMS messaging
** websockets peer to peer initiate
** GPS mapping
** Group messaging
** Group calls

* Note
Authenticated means the user has to send an authorization header in this format
#+BEGIN_SRC json
{
    "Authorization": "Bearer <access_token>"
}
#+END_SRC

* Endpoints
** Ping endpoint ~/ping GET~
- returns timestamp for measuring latency between client and server
  #+BEGIN_SRC json
    {"status":"ok","timestamp":1772410305.0920138}
  #+END_SRC
- this endpoint can be used like this
  #+BEGIN_SRC javascript
async function measureLatency() {
    const start = performance.now();
    await fetch("http://localhost:8000/ping");
    const end = performance.now();
    return end - start; // milliseconds
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}


(async ()=>{
    let successes = 0;
    for (let i = 0; i < 4; i++) {
        try {
            await measureLatency()
            successes++
        } catch {
            fails++
        }
        await sleep(1000)
    }
    console.log(`${successes/4 * 100}% success rate`) // if 3 of the 4 pings is a success then this will output -> 75% success rate
})()
#+END_SRC
** INFO Endpoint ~/ GET 1.1~
- returns a string if the API is running
- ~{"state": "running"}~

** INFO endpoint ~/auth GET~
- returns a string if the ~/auth~ endpoint is running
- ~{ 'status': 'auth endpoint is running properly' }~

** INFO point ~/auth/exists GET~
- returns a ~{exists: boolean}~ value to any of these fields: username,
  phone number, ID, or email
*** Sample Request
#+BEGIN_SRC json
<link>/auth/exists?identifier=<username, email, or phonenumber>
#+END_SRC
** Get Token Endpoint~/auth/token POST~
- this endpoint requires two form-data arguments:
  1. username
  2. password
- the ~username~ is actually an *email address*. It is named ~username~ as per compliance
  with the oauth2 standard
- the password is any string
** Create account endpoint ~/auth/ POST~
- this is an example form-data (body) that should be sent to the API
*** Sample Request
with form-data/request body
#+BEGIN_SRC json
{
    "first_name": "Test", // min=2, max=50
    "username": "TestUser", // min=2, max=50
    "last_name": "Test", // min=2, max=50
    "phone_number": "+23960206981",
    "email": "user@example.com",  // email string
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6", // UUID, optional
    "password": "Test1234" // min=8, max=128, with digits and upper and lower case letters
}
#+END_SRC
- the ~id~ field is optional
- the password field should have upper and lower case letter. At least one
  number is also required

*** Sample Response
#+BEGIN_SRC json
{
  "username": "johndoe3",
  "first_name": "John",
  "last_name": "Doe",
  "phone_number": null,
  "email": null,
  "id": "f5da3a69-26f7-464f-a3ae-bb25b8bfe124",
  "detail": "Account created.",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOm51bGwsImV4cCI6MTc3MjMyNTQ2Mn0.CeR0uAK3LG8Ewmrn_eWiGAW9W9OAjexE_8shb40I5XQ"
}
#+END_SRC

** Login ~/auth/token POST~
- this endpoint accepts two arguments: ~username~ and ~password~

*** Sample Request
with request body/form-data
#+BEGIN_SRC json
{
    "username": "TestUser",
    "password": "Test1234"
}
#+END_SRC
- the ~username~ field can be email, username, phone_number, or user id

*** Sample Response
#+BEGIN_SRC json
{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMS0wOTU0NkBnLmJhdHN0YXRlLXUuZWR1LnBoIiwiZXhwIjoxNzcxNDcxMzMxfQ.X4Xp250Zafs7mIXDvjPAASfQKZUG6MyEnYZJAzfRK4E",
  "token_type": "bearer"
}
#+END_SRC

** Generate recovery key ~/auth/forgot-password/generate-new-recovery-key POST~
  - this endpoint requires the user to be /authenticated/
  - no arguments required
  - response is the recovery file


** recovery account with recovery key ~/auth/forgot-password/recovery-with-recovery-key~
- requires two arguments
- recovery key expires after one use
*** Sample Request
with url parameter
#+BEGIN_SRC txt
<link>?user_identifier=<username_email_or_id>
#+END_SRC

with request body
#+BEGIN_SRC json
{
    key_file: File() // recovery file
}
#+END_SRC
*** Sample response
#+BEGIN_SRC json
{
    "recovery-link": "localhost:8000/auth/forgot-password/reset-password?token=EMs-6ZYdWMrpAkeMVK8hdLxfc65vJB6wjGXzEZ2xWrI",
    "method": "POST",
    "expire_in_seconds": 1800
}
#+END_SRC


** reset password ~/auth/forgot-password/reset-password GET~
- requires the ~token~ argument
- will give a ~detail~ response regarding request status
*** Sample Request
with URL parameter
#+BEGIN_SRC json
<link>?token=<token>
#+END_SRC
*** Sample response
  #+BEGIN_SRC json
{
    "detail": "Valid token. Use POST request."
}
  #+END_SRC


** reset password ~/auth/forgot-password/reset-password POST~
- requires the ~token~ argument
- will give a ~detail~ response regarding request status
*** Sample Request
with url parameter
#+BEGIN_SRC json
<link>?token=<token>
#+END_SRC
with request body
#+BEGIN_SRC json
{
  "new_password": "stringst" // new_password must have capital, lowecase, and a number. It's at least 8 characters long
}
#+END_SRC
*** Sample response
  #+BEGIN_SRC json
{
  "message": "password updated successfully."
}
  #+END_SRC

** forgot password ~/auth/forgot-password/email POST~
- sends email to user mail (the email includes a link to the /reset-password end
  point)
*** sample response
#+BEGIN_SRC json
{
    "message": "If the account exists, a reset link was sent."
}
#+END_SRC

** Add security questions ~/auth/forgot-password/security-questions POST~
This endpoint requires user to be authenticated
*** Sample Request
with form data (can be multiple question and answers in one request)
#+BEGIN_SRC json
[{
    "question": "What is your mother'\''s maiden name?",
    "answer": "Smith"
}]
#+END_SRC
*** Sample response
#+BEGIN_SRC json
{
  "message": "Security questions saved successfully."
}
#+END_SRC

** Get security questions ~/auth/forgot-password/security-question POST~
*** Sample Request
with url parameter
#+BEGIN_SRC json
<link>?identifier=johndoe
#+END_SRC
*** Sample response
#+BEGIN_SRC json
{
  "question": "What is your mother's maiden name?"
}
#+END_SRC

** Get security questions ~/auth/forgot-password/security-question/answer POST~
*** Sample Request
with url parameter
#+BEGIN_SRC json
<link>?identifier=johndoe
#+END_SRC

with request body/form-data
#+BEGIN_SRC json
{
  "question": "What is your mother's maiden name?",
  "answer": "Smith"
}
#+END_SRC

*** Sample response
#+BEGIN_SRC json
{
  "correct": true,
  "reset_link": "localhost:8000/auth/forgot-password/reset-password?token=iIVaJOGsKMpZL1hxg6uo3dFUyNv-P-beDSW3MCvgZ9s"
}
#+END_SRC

** Generate security question ~/auth/forgot-password/generate-security-question GET~
requires user to be authenticated
*** Sample Response
#+BEGIN_SRC json
{
  "question": "What's something that you believe that most other people don't?"
}
#+END_SRC
** Verify email ~/auth/verify/email GET~
requires token url parameter sent to a user email. Responds with an html page
** Verify email ~/auth/verify/resend-verification-email GET~
requires user to be authenticated

** Websocket/signalling
*** SDP relay example ~/ws GET~
- access like
  ~https://ylp-software.onrender.com/ws/?target_id=8380dbb9-482e-42fa-a1fd-fafedd9f918d&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOWM4ZDRlYS00OGYwLTRiN2UtYWY1Mi0yZDNmY2FkMGU2OGQiLCJleHAiOjE3NzI0NTU2MDh9.aD-vGqlRHdx_-zHm9Oev12VKCvOoU9MhLm-7rTLnNok&my_id=09c8d4ea-48f0-4b7e-af52-2d3fcad0e68d~.
  Notice the url parameters of my_id, target_id, and token (access_token).

*** SDP relay ~ws://localhost:8000/ws/~ (not visible on the docs)
- this is an endpoint that will be used for relaying SDP offers, answers, and
  ICE candidates
- this endpoint will accept sdp offers, sdp answers, and ICE candidates.
  Anything else will be rejected.
**** Sample Connection to websocket
  #+BEGIN_SRC json
  ws://localhost:8000/ws/?target_id=${client_id}&token=${token}
  #+END_SRC
  Put this link url (change domain as needed but it needs ws:// or wss:// at the
  protocol) inside a WebSocket object, then send a sdp message like
  #+BEGIN_SRC json
    {
        "type": "offer",
        "from_user": "550e8400e29b41d4a716446655440000",
        "to": "619176107fed4af4abb235dc9663136d",j
        "data":  {"some_data": {"here_like":"this"}}
    }
  #+END_SRC

  *Note that the ~from~ and ~to~ should be the same as the connection parameters*

***** TODO
****** ADD TYPES
  - ice-candidate
  - offer
  - answer
  - handshake
******  change structure
#+BEGIN_SRC
      {
        type: "";
        data: {
            from: UUID; to: UUID, ipAddress: string; port: number };
        }
#+END_SRC

** update user info ~/update/profile POST~
can take in different fields to update (can leave fields that won't be updated blank)
with request body/form-data
#+BEGIN_SRC json
{
  "username": "string", // optional
  "first_name": "string", // optional
  "last_name": "string", // optional
  "phone_number": "86410482368", // optional
  "email": "user@example.com" // optional
}
#+END_SRC
** Check if a sync is available of server ~/sync/check GET~
Requires users to be authenticated.

use this to check if updates are available from the server


send a request like
~http://localhost:8000/sync/check?last_sync=2026-03-30T06%3A24%3A50.565Z~

*** Sample response
#+BEGIN_SRC json
{
  "has_updates": false,
  "new_items_count": 0, // count of items to be synced
  "last_update_at": null // last updated timestamp
}
// OR
{
  "has_updates": true,
  "new_items_count": 12,
  "last_update_at": "2026-03-30T06:25:07.399Z"
}
#+END_SRC
** Sync from server ~/sync/ get~
Requires users to be authenticated.

Send a request like:
~http://localhost:8000/sync/?last_sync=2026-03-29T06%3A16%3A02.446Z&limit=50~
*** /last_sync/ argument
- meant to be the point where the syncing will start
*** /limit/ argument
- amount of data that will be sync in the current connection
- a device can send multiple sync request if there are a lot of data to sync
  from server

*** Example response
#+BEGIN_SRC json
{
  "server_time": "2026-03-30T06:16:25.686453Z", // shows the current time in the server (could be used as a comparison to the current device's time)
  "conversations": [],              // field for conversations to be synced
  "messages": [],                   // field for messages to be synced
  "calls": [],                      // field for calls to be synced
  "call_participants": [], [],      // field for call participants to be synced
  "conversation_participants": [    // field for conversation participants to be synced
    {
      "conversation_id": "252ad3d9-4b9a-4ad3-b604-a11b3019b85d",
      "id": "ef866642-8997-41db-a286-3bee85d488ae",
      "joined_at": "2026-03-30T02:05:20.311407",
      "user_id": "da055078-37e6-4106-9a64-5e0b0b001b6b",
      "is_deleted": false
    },
    {
      "conversation_id": "252ad3d9-4b9a-4ad3-b604-a11b3019b85d",
      "id": "ef866642-8997-41db-a286-3bee85d488be",
      "joined_at": "2026-03-30T02:05:20.311407",
      "user_id": "96b72839-e077-4413-91e6-d3038c6a9532",
      "is_deleted": false
    }
  ],
  "message_receipts": [],  // field for message receipts to be synced
  "new_cursor": "2026-03-30T06:16:25.686389Z", // can be used as the new 'last_synced' value for syncing to the server
  "has_more": false // shows true if there's more unsynced data in the server, otherwise false
}
#+END_SRC

** Sync to server ~/sync/push POST~
Requires users to be authenticated.


use this endpoint to push new data to the server
*** attach the following as the form-body
#+BEGIN_SRC json
{
  "conversations": [...],
  "messages": [...],
  "conversation_participants": [...],
  "calls": [...],
  "call_participants": [...],
  "message_receipts": [...]
}
#+END_SRC
*** Sample response

#+BEGIN_SRC json
{
  "status": "success",
  "message": "Data reconciled"
}
#+END_SRC

*** Sample data to send (same data format will be sent when syncing from server)
#+BEGIN_SRC python
    push_payload = {
        "conversations": [
            {
                "id": conv_id,
                "title": "Sync Test",
                "conversation_type": "group",
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
        ],
        "conversation_participants": [
            {
                "id": part_id,
                "conversation_id": conv_id,
                "user_id": user_id,
                "joined_at": datetime.now(timezone.utc).isoformat(),
                "is_deleted": False
            }
        ],
        "messages": [
            {
                "id": msg_id,
                "conversation_id": conv_id,
                "content": "Reconciliation check",
                "message_type": "text",
                "is_deleted": False,
                "created_at": datetime.now(timezone.utc).isoformat()
            }
        ],
        "calls": [
            {
                "id": str(call_id),
                "call_type": "video",  # CallType.AUDIO
                "status": "completed", # StatusType.COMPLETED
                "start_time": datetime.now(timezone.utc).isoformat(),
                "end_time": datetime.now(timezone.utc).isoformat(),
                "conversation_id": str(conv_id),
                "initiator_id": str(user_id)
            }
        ],
        "call_participants": [
            {
                "id": str(uuid4()),
                "conversation_id": str(conv_id),
                "user_id": str(user_id),
                "joined_at": datetime.now(timezone.utc).isoformat(),
                "left_at": None
            }
        ],
        "message_receipts": [
            {
                "id": str(uuid4()),
                "status": "read", # StatusType.READ
                "message_id": str(msg_id),
                "user_id": str(user_id),
                "updated_at": datetime.now(timezone.utc).isoformat()
            }
        ]
    }
#+END_SRC
