#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerate postman/collections/*.postman_collection.json from docs/api/openapi/*.yaml.
#
# docs/api/openapi/*.yaml is the source of truth (generated from the live FastAPI
# app by scripts/generate_openapi_docs.py, drift-checked in CI). This script merges
# those 12 fragments into a single OpenAPI document -- tagging every operation with
# its fragment name so the Postman converter groups requests into matching folders
# -- then hands that off to `openapi-to-postmanv2` to produce the collection.
#
# Requires: Ruby stdlib only, plus `npx` (Node) to run openapi-to-postmanv2.
#
# Usage:
#   ruby scripts/generate_postman_collection.rb

require "yaml"
require "json"
require "fileutils"
require "digest"
require "open3"
require "tmpdir"

REPO_ROOT = File.expand_path("..", __dir__)
OPENAPI_DIR = File.join(REPO_ROOT, "docs", "api", "openapi")
POSTMAN_DIR = File.join(REPO_ROOT, "postman")
COLLECTIONS_DIR = File.join(POSTMAN_DIR, "collections")

def merge_openapi_fragments
  merged = nil

  Dir.glob(File.join(OPENAPI_DIR, "*.yaml")).sort.each do |path|
    fragment_name = File.basename(path, ".yaml")
    spec = YAML.safe_load(File.read(path))

    (spec["paths"] || {}).each_value do |methods|
      methods.each_value do |operation|
        next unless operation.is_a?(Hash)

        operation["tags"] = [fragment_name]
      end
    end

    if merged.nil?
      merged = spec
    else
      merged["paths"] ||= {}
      merged["paths"].merge!(spec["paths"] || {})

      merged["components"] ||= {}
      (spec["components"] || {}).each do |kind, definitions|
        merged["components"][kind] ||= {}
        merged["components"][kind].merge!(definitions)
      end
    end
  end

  merged["info"]["title"] = "SAPOT API"
  merged["info"].delete("description")
  merged
end

# `openapi-to-postmanv2` assigns a fresh UUID to every collection/folder/request
# on each run, which makes the checked-in JSON churn on every regeneration even
# when nothing changed. Replace them with UUIDv5-style values (deterministic,
# derived from stable identity: title/name/method+path) so re-exports diff cleanly.
def stabilize_ids!(node, path = "root")
  case node
  when Hash
    if node.key?("_postman_id") || node.key?("id")
      identity = node["name"] || path
      stable_id = Digest::MD5.hexdigest("sapot-postman:#{path}:#{identity}")
      node["_postman_id"] = stable_id if node.key?("_postman_id")
      node["id"] = stable_id if node.key?("id")
    end

    node.each { |key, value| stabilize_ids!(value, "#{path}/#{key}") }
  when Array
    node.each_with_index { |value, index| stabilize_ids!(value, "#{path}[#{index}]") }
  end
end

# Baseline assertions applied to every generated request.
#
# Deliberately lenient. openapi-to-postmanv2 fakes request bodies from the
# schema, so a large share of POST/PATCH/DELETE requests legitimately 4xx --
# asserting exact status codes here would just encode the faker's output. What
# this catches is unhandled exceptions and hangs, across all 121 endpoints.
# Exact-behavior assertions live in the hand-authored postman/flows/ collections.
#
# Content-Type is checked conditionally rather than asserted: /download/download-apk
# streams a file and the profile-photo endpoints return images, so "always JSON"
# would be wrong.
BASELINE_TEST_SCRIPT = <<~JAVASCRIPT
  // Generated by scripts/generate_postman_collection.rb. Do not hand-edit --
  // regenerating overwrites this file.
  pm.test("does not return a server error", function () {
      pm.expect(pm.response.code).to.be.below(500);
  });

  pm.test("responds within 5s", function () {
      pm.expect(pm.response.responseTime).to.be.below(5000);
  });

  pm.test("a JSON content-type means a parseable JSON body", function () {
      var contentType = pm.response.headers.get("Content-Type") || "";
      if (contentType.indexOf("application/json") === -1) {
          return;
      }
      if (pm.response.text().length === 0) {
          return;
      }
      pm.response.to.be.json;
  });
JAVASCRIPT

BASELINE_TEST_EVENT = {
  "listen" => "test",
  "script" => {
    "type" => "text/javascript",
    "exec" => BASELINE_TEST_SCRIPT.split("\n")
  }
}.freeze

# openapi-to-postmanv2 emits a per-operation "auth" block on some requests
# (derived from each OpenAPI operation's own security scheme). That overrides
# the collection-level bearer auth set in `main` -- Postman only inherits
# parent auth when the request has no "auth" key at all. Left in place, those
# requests never receive the minted {{token}}, so most authenticated endpoints
# in the generated collections would 401 instead of exercising real handler
# logic, defeating the point of seeding fixtures and minting a token before a
# full run. Strip it so every request falls back to the collection's bearer
# auth.
#
# Strips "oauth2" (what the converter emits for a secured operation) and the
# bare `"auth": null` it emits for an operation with no security requirement --
# neither should override the collection-level bearer auth. Only an explicit
# `{"type": "noauth"}` block is left in place: a future OpenAPI fragment with
# `security: []` could convert to that, and stripping it would silently start
# sending the admin bearer token to a deliberately public endpoint.
def strip_item_auth!(items)
  items.each do |item|
    if item.key?("item")
      strip_item_auth!(item["item"])
      next
    end

    next unless item["request"].is_a?(Hash)
    next unless item["request"].key?("auth")

    auth = item["request"]["auth"]
    item["request"].delete("auth") unless auth.is_a?(Hash) && auth["type"] == "noauth"
  end
end

# Returns a deep copy of the collection with the baseline test event attached to
# every request item. Marshal round-trip is the stdlib deep-copy idiom; the
# collection is plain JSON-derived Hashes and Arrays, so it round-trips cleanly.
def with_baseline_tests(collection)
  copy = Marshal.load(Marshal.dump(collection))
  attach_baseline_tests!(copy["item"])
  copy
end

def attach_baseline_tests!(items)
  items.each do |item|
    if item.key?("item")
      attach_baseline_tests!(item["item"])
      next
    end

    # Drop any prior test listener before adding ours, so re-running the
    # generator over already-generated output doesn't stack duplicates.
    existing = (item["event"] || []).reject { |event| event["listen"] == "test" }
    item["event"] = existing + [Marshal.load(Marshal.dump(BASELINE_TEST_EVENT))]
  end
end

# Split the converted collection into one standalone collection per top-level
# folder, so each OpenAPI fragment gets its own reviewable file instead of all
# 121 requests landing in a single 766 KB blob.
#
# Returns a new Hash rather than mutating the input: `main` still needs the
# merged collection intact, and a pure function is what the test can pin down.
#
# Call this AFTER stabilize_ids! -- that function derives IDs from each node's
# path within the document, so splitting first would change every path and
# churn all 121 request IDs for nothing.
def split_by_folder(collection)
  shared = collection.reject { |key, _| key == "item" }

  collection["item"].each_with_object({}) do |folder, out|
    # Top-level entries without a nested "item" are loose requests, not
    # folders. folderStrategy: "Tags" shouldn't produce any, but an untagged
    # operation slipping through shouldn't crash the generator.
    next unless folder.key?("item")

    category = folder["name"]

    out[category] = shared.merge(
      "info" => shared["info"].merge(
        "name" => "SAPOT API - #{category}",
        # Distinct per file, or Postman treats all 12 as the same collection
        # on import and silently overwrites.
        "_postman_id" => Digest::MD5.hexdigest("sapot-postman:collection:#{category}")
      ),
      "item" => folder["item"]
    )
  end
end

def main
  FileUtils.mkdir_p(COLLECTIONS_DIR)

  merged_spec = merge_openapi_fragments
  merged_json_path = File.join(Dir.tmpdir, "sapot-openapi-merged.json")
  File.write(merged_json_path, JSON.pretty_generate(merged_spec))

  # Group requests into folders by the fragment tag (matching docs/api/openapi/*.yaml
  # groupings), not the default per-path-segment layout. Those folders become the
  # split boundary below.
  options_config_path = File.join(Dir.tmpdir, "sapot-openapi-postman-options.json")
  File.write(options_config_path, JSON.generate({ folderStrategy: "Tags" }))

  # Convert into a temp file, not into postman/: the merged collection is an
  # intermediate now, and only the split files are committed.
  converted_path = File.join(Dir.tmpdir, "sapot-postman-merged.json")

  stdout, stderr, status = Open3.capture3(
    "npx", "--yes", "openapi-to-postmanv2",
    "-s", merged_json_path,
    "-o", converted_path,
    "-c", options_config_path,
    "-p"
  )
  unless status.success?
    warn stdout
    warn stderr
    abort "openapi-to-postmanv2 failed"
  end

  collection = JSON.parse(File.read(converted_path))
  stabilize_ids!(collection)

  # Let every request inherit a bearer token from the active environment instead
  # of requiring per-request auth setup (token obtained via /auth/token, see README).
  collection["auth"] = {
    "type" => "bearer",
    "bearer" => [{ "key" => "token", "value" => "{{token}}", "type" => "string" }]
  }

  strip_item_auth!(collection["item"])
  collection = with_baseline_tests(collection)

  split_by_folder(collection).each do |category, sub_collection|
    path = File.join(COLLECTIONS_DIR, "#{category}.postman_collection.json")
    File.write(path, "#{JSON.pretty_generate(sub_collection)}\n")
    puts "Wrote #{path}"
  end
ensure
  [merged_json_path, options_config_path, converted_path].each do |path|
    File.delete(path) if path && File.exist?(path)
  end
end

main if __FILE__ == $PROGRAM_NAME
