@startuml lan-call
actor User
participant ClientApp
participant CallService
participant ConnectionService
participant WebrtcAdapter

User-> ClientApp: clicks chat room
activate ClientApp
ClientApp->ConnectionService: connect to peer
activate ConnectionService
ref over ConnectionService: connect to the peer
ConnectionService-->ClientApp: connected sucessfully

User->ClientApp: Call to peer
ClientApp->CallService: inform callee
activate CallService
CallService->ConnectionService: send message
ref over ConnectionService: send message

ClientApp->CallService: start call
group start call
    CallService->ConnectionService: initialize local stream
    ConnectionService->WebrtcAdapter: initialize local stream
    activate WebrtcAdapter

    CallService->ConnectionService: renegotiate with peer
    group renegotiate
        ConnectionService->WebrtcAdapter: create offer
        WebrtcAdapter->ConnectionService: return offer
        ConnectionService->ConnectionService: send offer message
        ref over ConnectionService: send message
        ref over ConnectionService: establish webrtc connection to the peer
    end
end

group handle incoming call
    ConnectionService->WebrtcAdapter: initialize local stream
    ConnectionService-->ClientApp: recieves incoming call
    ClientApp->ClientApp: redirect to call room
end


@enduml