@startuml lan-messaging
actor User
participant ClientApp
participant ChatService
participant ConnectionService
participant PeerService
participant DiscoveryService
participant LocalDatabase
participant WebRTCAdapter
participant ZeroconfAdapter
participant TCPClientAdapter
participant TCPServerAdapter


User -> ClientApp: clicks chat room with peer
activate ClientApp
group connect
    ClientApp -> ClientApp: get the ID of the peer
    ClientApp -> ChatService: connect to the peer with ID
    activate ChatService
    ChatService -> PeerService: get the peer in the database via ID

    activate PeerService
    PeerService -> LocalDatabase: get the peer
    activate LocalDatabase
    LocalDatabase --> PeerService: returns peer
    deactivate LocalDatabase
    PeerService--> ChatService: returns peer
    ChatService->ChatService: initialize the peer property

    ChatService -> PeerService: get the discovered peer via ID
    PeerService -> PeerService: get the discovered peer
    PeerService --> ChatService: returns discovered peer
    deactivate PeerService

    ChatService -> ConnectionService: connect to the peer via IP and port
    activate ConnectionService
    ref over ConnectionService : peer to peer connection
    ConnectionService --> ChatService: connected successfully
    deactivate ConnectionService
    ChatService --> ClientApp: connected successfully
    deactivate ClientApp
end


User -> ClientApp: send message
activate ClientApp
ClientApp -> ChatService: send message to the peer
group ensure conversation initialized
    ChatService->LocalDatabase: check if conversation with the peer exists
    activate LocalDatabase
    LocalDatabase-->ChatService: returns boolean if conversation exists
    alt if conversation exists
        ChatService->LocalDatabase: get the conversation
        LocalDatabase-->ChatService: returns conversation
        ChatService->ChatService: initialize the conversation property
    else
        ChatService->LocalDatabase: create conversation
        LocalDatabase-->ChatService: returns conversation
        ChatService->ChatService: initialize the conversation property
    end
end

group create message
    ChatService->LocalDatabase: save message
    LocalDatabase->ChatService: returns message
    ChatService->LocalDatabase: save message status with the status of SENDING
    LocalDatabase->ChatService: returns message status
end

group send chat message
    ChatService->ConnectionService: send chat message
    ConnectionService->WebRTCAdapter: send chat message
    activate WebRTCAdapter

    alt if send message success
        WebRTCAdapter-->ConnectionService: sending message success
        ConnectionService-->ChatService: inform sending sucess
        ChatService->LocalDatabase: update message status with SENT
    else
        WebRTCAdapter-->ConnectionService: sending message failed
        ConnectionService-->ChatService: inform sending failed
        ChatService->LocalDatabase: update message status with NOT_SENT
    end
end

group handle incoming message
    WebRTCAdapter-->ConnectionService: recieves message
    activate ConnectionService
    ConnectionService->ChatService: handle incoming message
    ChatService->PeerService: get peer by ID
    activate PeerService
    PeerService->LocalDatabase: get peer
    LocalDatabase-->PeerService: return peer
    PeerService-->ChatService: return peer
    group get or create conversation for incoming message
        ChatService->LocalDatabase: check if conversation exists between peer
        LocalDatabase-->ChatService: return boolean if coversation exists

        alt if conversation exists
            ChatService->LocalDatabase: get conversation
            LocalDatabase-->ChatService: return conversation
        else
            group create chat room
                ChatService->LocalDatabase: save conversation
                ChatService->LocalDatabase: save conversation participants
            end

        end
    end

    ChatService->LocalDatabase: save incoming message
    ChatService->ConnectionService: send acknowledge message
end

deactivate PeerService

group hanlde ack message
    WebRTCAdapter-->ConnectionService: recieves ack message
    deactivate WebRTCAdapter
    ConnectionService->LocalDatabase: update message status to be DELIVERED
end

group perform resend message for peer
    ZeroconfAdapter-->DiscoveryService: return discovered peer
    activate ZeroconfAdapter
    deactivate ZeroconfAdapter
    activate DiscoveryService
    DiscoveryService->LocalDatabase: get all not sent message for the discovered peer
    LocalDatabase-->DiscoveryService: return all not sent message
    DiscoveryService->ChatService: resend message
    group try resend message
        ChatService->ConnectionService: connect to peer
        ref over ConnectionService: peer to peer connection
        alt if connection success
            ConnectionService-->ChatService: connected successfully
        else
            ConnectionService-->ChatService: connection failed
            ChatService-->DiscoveryService: resend failed
        end

        ChatService->ConnectionService: send chat message
        ref over ConnectionService: send chat message
        alt if sending chat message success
            ConnectionService-->ChatService: send successfully
        else
            ConnectionService-->ChatService: send failed
            ChatService-->DiscoveryService: resend failed
        end
        ChatService->LocalDatabase: update message status to be SENT
    end
end

deactivate ConnectionService
deactivate LocalDatabase

@enduml