@startuml Peer to peer connection
actor UserA
participant ClientApp
participant DiscoveryService
participant WebRTCAdapter
participant TCPServerAdapter
participant TCPClientAdapter
participant ConnectionService
participant UserBClientApp

UserA -> ClientApp: start application
activate ClientApp

ClientApp -> ConnectionService: start listening to TCP server
activate ConnectionService
UserBClientApp -> ConnectionService: start listening to TCP server
activate  UserBClientApp

ClientApp -> DiscoveryService: make the device discovered by others
activate DiscoveryService
UserBClientApp -> DiscoveryService: make the device discovered by others

ClientApp -> DiscoveryService: discover all peers on the LAN
UserBClientApp -> DiscoveryService: discover all peers on the LAN

DiscoveryService -> DiscoveryService: store UUID, IP address, username and port of discovered peers

DiscoveryService --> UserBClientApp: display discovered peer's username
DiscoveryService --> ClientApp: display discovered peer's username
deactivate DiscoveryService

UserA -> ClientApp: connect to B
ClientApp -> DiscoveryService: get IP address and port of B

alt if the peer exists
    DiscoveryService --> ClientApp: returns IP address and port
else if not
    DiscoveryService --> ClientApp: connection failed
end

ClientApp->ConnectionService: connect to TCP server of B with IP address and port

alt if connect success
    ConnectionService--> ClientApp: TCP connection success
else
    ConnectionService--> ClientApp: TCP connection failed
end


ConnectionService -> TCPClientAdapter: send handshake message to B
activate TCPClientAdapter

group B handle connection to A
    TCPServerAdapter --> ConnectionService: recieves handshake message from A containing A's IP and port
    activate TCPServerAdapter
    ConnectionService -> ConnectionService: connect to A with IP and port
end


ConnectionService -> WebRTCAdapter: create WebRTC offer message
activate WebRTCAdapter
WebRTCAdapter -> WebRTCAdapter: create WebRTC peer connection
WebRTCAdapter -> WebRTCAdapter: generate offer message
WebRTCAdapter --> ConnectionService: returns offer message
ConnectionService -> TCPClientAdapter: send offer message to B

group B handle offer message of A
    TCPServerAdapter --> ConnectionService: recieves offer message from A
    ConnectionService -> WebRTCAdapter: handle offer message
    WebRTCAdapter -> WebRTCAdapter: generate answer
    WebRTCAdapter --> ConnectionService: returns answer
    ConnectionService -> TCPClientAdapter: send answer message to A
end

TCPServerAdapter --> ConnectionService: recieves answer message from B
deactivate TCPServerAdapter
ConnectionService --> WebRTCAdapter: handle answer message
WebRTCAdapter --> WebRTCAdapter: add ice candidaates

WebRTCAdapter -> ConnectionService: WebRTC Connection established
deactivate WebRTCAdapter

ConnectionService --> ClientApp: connection established
deactivate ClientApp
ConnectionService --> UserBClientApp: connection established


deactivate ConnectionService
deactivate UserBClientApp

@enduml